FROM debian:latest

RUN apt-get -y update
RUN apt-get -y install \
	build-essential \
	checkinstall \
	cmake \
	curl \
	git \
	wget \
	unzip \
	imagemagick \
	libatlas-base-dev \
	libgtk2.0-dev pkg-config \
	libtbb2 \
	libtbb-dev \
	libjpeg-dev \
	libpng-dev \
	libtiff-dev \
	libjasper-dev \
	libswscale-dev \
	libavcodec-dev \
	libavformat-dev

